# Generated by Django 5.2.5 on 2025-09-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('sup', 'Superuser'), ('admin', 'Administrator'), ('user', 'User')], default='user', max_length=8),
        ),
    ]
