# Generated by Django 5.2.5 on 2025-08-29 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TensorFlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=16)),
                ('model_version', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=32)),
                ('board_name', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=64)),
                ('address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=16)),
                ('resolution', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='databaseApp.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128)),
                ('checksum', models.CharField(max_length=128)),
                ('image_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.imageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TensorFlowOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('person_count', models.IntegerField()),
                ('is_processed', models.BooleanField()),
                ('image_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allInfo', to='databaseApp.imageinfo')),
                ('tensorFlow_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='databaseApp.tensorflowmodel')),
            ],
        ),
    ]
