# Generated by Django 5.2.5 on 2025-09-08 18:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128)),
                ('checksum', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TensorFlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=16)),
                ('model_version', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='TensorFlowOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('person_count', models.IntegerField()),
                ('is_processed', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(max_length=32)),
                ('board_name', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=64)),
                ('address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('confidence_threshold', models.FloatField(default=0.1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.tensorflowmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=16)),
                ('resolution', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='databaseApp.camera')),
                ('storage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.storage')),
                ('output', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.tensorflowoutput')),
            ],
        ),
    ]
