# Generated by Django 5.2.5 on 2025-08-14 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TensorFlowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelName', models.CharField(max_length=16)),
                ('modelVersion', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameraName', models.CharField(max_length=32)),
                ('boardName', models.CharField(max_length=32)),
                ('location', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128)),
                ('fileSize', models.BigIntegerField()),
                ('fileType', models.CharField(max_length=16)),
                ('resolution', models.CharField(max_length=16)),
                ('timestamp', models.DateTimeField()),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='databaseApp.camera')),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128)),
                ('checksum', models.CharField(max_length=128)),
                ('imageInfo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='databaseApp.imageinfo')),
            ],
        ),
        migrations.CreateModel(
            name='TensorFlowOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.FloatField()),
                ('personCount', models.IntegerField()),
                ('isProcessed', models.BooleanField()),
                ('imageInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allInfo', to='databaseApp.imageinfo')),
                ('tensorFlowModel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='databaseApp.tensorflowmodel')),
            ],
        ),
    ]
