# Generated by Django 5.2.5 on 2025-09-08 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tensorflowmodel',
            name='model_url',
            field=models.URLField(default='https://tfhub.dev/tensorflow/ssd_mobilenet_v2/2'),
            preserve_default=False,
        ),
    ]
