# Generated by Django 5.2.5 on 2025-08-16 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='address',
            field=models.GenericIPAddressField(default='0.0.0.0', protocol='IPv4', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='databaseApp.camera'),
        ),
    ]
