# Generated by Django 5.2.5 on 2025-09-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0002_tensorflowmodel_model_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='model',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='databaseApp.tensorflowmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tensorflowmodel',
            name='model_name',
            field=models.CharField(max_length=32),
        ),
    ]
