# Generated by Django 5.2.5 on 2025-09-09 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0003_imageinfo_model_alter_tensorflowmodel_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tensorflowoutput',
            name='is_processed',
        ),
        migrations.AddField(
            model_name='camera',
            name='process_image',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='imageinfo',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
