# Generated by Django 5.2.5 on 2025-09-09 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0004_remove_tensorflowoutput_is_processed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageinfo',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseApp.tensorflowmodel'),
        ),
        migrations.AlterField(
            model_name='imageinfo',
            name='output',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='databaseApp.tensorflowoutput'),
        ),
    ]
