# Generated by Django 5.2.5 on 2025-09-11 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0006_camera_admins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storage',
            name='checksum',
        ),
    ]
