# Generated by Django 5.2.5 on 2025-09-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0007_remove_storage_checksum'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='user_directory',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
