# Generated by Django 5.2.5 on 2025-09-13 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0008_storage_user_directory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage',
            old_name='user_directory',
            new_name='camera_directory',
        ),
    ]
