# Generated by Django 5.2.5 on 2025-10-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseApp', '0009_rename_user_directory_storage_camera_directory'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='resolution',
            field=models.CharField(default='1600x1200', max_length=16),
            preserve_default=False,
        ),
    ]
